# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giulio/scacchiera_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giulio/scacchiera_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giulio/scacchiera_cpp/CMakeFiles /home/giulio/scacchiera_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giulio/scacchiera_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named Pawn7

# Build rule for target.
Pawn7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pawn7
.PHONY : Pawn7

# fast build rule for target.
Pawn7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn7.dir/build.make CMakeFiles/Pawn7.dir/build
.PHONY : Pawn7/fast

#=============================================================================
# Target rules for targets named Rook

# Build rule for target.
Rook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rook
.PHONY : Rook

# fast build rule for target.
Rook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/build
.PHONY : Rook/fast

#=============================================================================
# Target rules for targets named Board

# Build rule for target.
Board: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Board
.PHONY : Board

# fast build rule for target.
Board/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/build
.PHONY : Board/fast

#=============================================================================
# Target rules for targets named Pawn2

# Build rule for target.
Pawn2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pawn2
.PHONY : Pawn2

# fast build rule for target.
Pawn2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn2.dir/build.make CMakeFiles/Pawn2.dir/build
.PHONY : Pawn2/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/Board.cpp.s
.PHONY : Board.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.s
.PHONY : main.cpp.s

pieces/Pawn2.o: pieces/Pawn2.cpp.o

.PHONY : pieces/Pawn2.o

# target to build an object file
pieces/Pawn2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn2.dir/build.make CMakeFiles/Pawn2.dir/pieces/Pawn2.cpp.o
.PHONY : pieces/Pawn2.cpp.o

pieces/Pawn2.i: pieces/Pawn2.cpp.i

.PHONY : pieces/Pawn2.i

# target to preprocess a source file
pieces/Pawn2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn2.dir/build.make CMakeFiles/Pawn2.dir/pieces/Pawn2.cpp.i
.PHONY : pieces/Pawn2.cpp.i

pieces/Pawn2.s: pieces/Pawn2.cpp.s

.PHONY : pieces/Pawn2.s

# target to generate assembly for a file
pieces/Pawn2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn2.dir/build.make CMakeFiles/Pawn2.dir/pieces/Pawn2.cpp.s
.PHONY : pieces/Pawn2.cpp.s

pieces/Pawn7.o: pieces/Pawn7.cpp.o

.PHONY : pieces/Pawn7.o

# target to build an object file
pieces/Pawn7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn7.dir/build.make CMakeFiles/Pawn7.dir/pieces/Pawn7.cpp.o
.PHONY : pieces/Pawn7.cpp.o

pieces/Pawn7.i: pieces/Pawn7.cpp.i

.PHONY : pieces/Pawn7.i

# target to preprocess a source file
pieces/Pawn7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn7.dir/build.make CMakeFiles/Pawn7.dir/pieces/Pawn7.cpp.i
.PHONY : pieces/Pawn7.cpp.i

pieces/Pawn7.s: pieces/Pawn7.cpp.s

.PHONY : pieces/Pawn7.s

# target to generate assembly for a file
pieces/Pawn7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn7.dir/build.make CMakeFiles/Pawn7.dir/pieces/Pawn7.cpp.s
.PHONY : pieces/Pawn7.cpp.s

pieces/Rook.o: pieces/Rook.cpp.o

.PHONY : pieces/Rook.o

# target to build an object file
pieces/Rook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/pieces/Rook.cpp.o
.PHONY : pieces/Rook.cpp.o

pieces/Rook.i: pieces/Rook.cpp.i

.PHONY : pieces/Rook.i

# target to preprocess a source file
pieces/Rook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/pieces/Rook.cpp.i
.PHONY : pieces/Rook.cpp.i

pieces/Rook.s: pieces/Rook.cpp.s

.PHONY : pieces/Rook.s

# target to generate assembly for a file
pieces/Rook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/pieces/Rook.cpp.s
.PHONY : pieces/Rook.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Board"
	@echo "... Main"
	@echo "... Pawn2"
	@echo "... Pawn7"
	@echo "... Rook"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pieces/Pawn2.o"
	@echo "... pieces/Pawn2.i"
	@echo "... pieces/Pawn2.s"
	@echo "... pieces/Pawn7.o"
	@echo "... pieces/Pawn7.i"
	@echo "... pieces/Pawn7.s"
	@echo "... pieces/Rook.o"
	@echo "... pieces/Rook.i"
	@echo "... pieces/Rook.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

